### PR TITLE
added stan install script for Dockerfile.gpu

### PR DESCRIPTION
**Pull request by RobJY**
Followed instructions from: https://mc-stan.org/docs/2_24/cmdstan-guide/cmdstan-installation.html
and works with test in the Trouble-shooting section.

I'm now looking for R stan example to verify it's working in R.

### CODE REVIEW

**Comment by RobJY** [comment]
I was thinking the link above was the one you sent me via Slack, but it's referenced in that page.  Now I'm working on trying the examples in: https://mc-stan.org/cmdstanr/articles/opencl.html that you sent

**Comment by RobJY** [comment]
The changes to this branch are not needed.

One can simply run the following 3 commands to install the needed package:

1. `install.packages("cmdstanr", repos = c("https://mc-stan.org/r-packages/", getOption("repos")))`
2. `library(cmdstanr)`
3. `install_cmdstan()`

After doing the above, all commands in the example on https://mc-stan.org/cmdstanr/articles/opencl.html will work

Should this be installed by the user or added to a new or existing install script?

**Comment by noamross** [comment]
Excellent.  Yes, let's let the user handle this if it works.  One less maintenance requirement.

**Comment by RobJY** [comment]
sounds great to me.  thanks!

**Pull request closed without merging**
